### ISSUE TITLE
没有考虑demand为0的情况

### ISSUE THREAD

**Issue by yc-cui** [diphosphane/CodeCraft2022-benchmark#1]
![image](https://user-images.githubusercontent.com/68642492/158352151-661fe0cb-f4fe-4059-83cc-f4ae31d01aa8.png)
任务书说明上是允许这种情况的：
![image](https://user-images.githubusercontent.com/68642492/158352212-0a3bbe58-7fa5-4f57-bf5d-66efdc063b4e.png)

**Comment by diphosphane** [comment]
fixed
