### ISSUE TITLE
一个小小的疑问

### ISSUE THREAD

**Issue by NU-LL** [diphosphane/CodeCraft2022-benchmark#4]
下面这里
https://github.com/diphosphane/CodeCraft2022-benchmark/blob/dda9625d9c508812ed7c611ff03292b84349ef5c/benchmark.py#L425
和这里
https://github.com/diphosphane/CodeCraft2022-benchmark/blob/dda9625d9c508812ed7c611ff03292b84349ef5c/benchmark.py#L437
是不是应该将`!=`该为`>`呢？

**Comment by diphosphane** [comment]
不是。客户端的带宽需求必须一致。
